"""unique constraint on produto.nome

Revision ID: 71cb919c0c45
Revises: dc5295b3ae4c
Create Date: 2026-06-09 17:16:11.483959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cb919c0c45'
down_revision = 'dc5295b3ae4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_produto_nome', ['nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint('uq_produto_nome', type_='unique')

    # ### end Alembic commands ###
