"""add forma_pagamento e observacao

Revision ID: b39127f12287
Revises: bfaf93aaf032
Create Date: 2026-06-05 22:47:24.101066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39127f12287'
down_revision = 'bfaf93aaf032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('observacao')
        batch_op.drop_column('forma_pagamento')

    # ### end Alembic commands ###
