"""add taxa_configuracao e taxas na venda

Revision ID: dc5295b3ae4c
Revises: ef4fd57ecb96
Create Date: 2026-06-06 14:48:11.520366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5295b3ae4c'
down_revision = 'ef4fd57ecb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxa_percentual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('taxa_valor', sa.Float(), nullable=True))

    op.create_table(
        'taxa_configuracao',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('forma_pagamento', sa.String(length=20), nullable=False),
        sa.Column('taxa_percentual', sa.Float(), nullable=False, server_default='0'),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('forma_pagamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('taxa_valor')
        batch_op.drop_column('taxa_percentual')

    op.drop_table('taxa_configuracao')
    # ### end Alembic commands ###
